@startuml
!theme materia-outline
skinparam componentStyle uml1
skinparam linetype polyline

skinparam interfaceBackgroundColor #white
skinparam interfaceBorderColor #DodgerBlue
skinparam interfaceBorderThickness 2

skinparam arrowLollipopColor #White

component us_search_ms as us_search_ms
database us_search_db as us_search_db
interface REST as search_rest

us_search_ms -d- us_search_db
us_search_ms -u- search_rest

@enduml