@startuml
!theme materia-outline
skinparam componentStyle uml1
skinparam linetype polyline

skinparam interfaceBackgroundColor #white
skinparam interfaceBorderColor #DodgerBlue
skinparam interfaceBorderThickness 2

skinparam arrowLollipopColor #White

component us_sesion_ms
database us_sesion_db
interface REST as session_rest

us_sesion_ms -d- us_sesion_db
us_sesion_ms -u- session_rest

@enduml