@startuml
!theme materia-outline
skinparam componentStyle uml1
skinparam linetype polyline

skinparam interfaceBackgroundColor #white
skinparam interfaceBorderColor #DodgerBlue
skinparam interfaceBorderThickness 2

skinparam arrowLollipopColor #White

entity "Users" as e01 {


*Uuid : Varchar
Email : Varchar
Status : Varchar
Password : Varchar
}
@enduml